#server:
#  port: 8282
#
#spring:
#  application:
#    name: RABBITMQ-PRODUCER
#
#
#  rabbitmq:
#    host: localhost
#    username: guest
#    password: guest
#    port: 5672
#    template:
#      routing-key: remitguru_routingkey
#      exchange: remitguru_exchange
#      default-receive-queue: remitguru_queue
#
